# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Inject code product quiz"
client_id = "f7c05bd5565a6ef28c53f6db540d5d9a"
application_url = "https://inject-code-product-quiz--development.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://inject-code-product-quiz--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
dev_store_url = "vevol-development.myshopify.com"
